In [2]:
def eip_quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return eip_quicksort(left) + middle + eip_quicksort(right)

print(eip_quicksort([3,6,8,10,1,2,1]))
#you can only use these variables: eip, mlblr, eip_in, eip_out, mlblr_in, mlblr_out, eip_list, eip_dict.

[1, 1, 2, 3, 6, 8, 10]


In [4]:
mlblr = 3
print(type(mlblr)) # Prints "<class 'int'>"
print(mlblr)       # Prints "3"
print(mlblr + 1)   # Addition; prints "4"
print(mlblr - 1)   # Subtraction; prints "2"
print(mlblr * 2)   # Multiplication; prints "6"
print(mlblr ** 2)  # Exponentiation; prints "9"
mlblr += 1
print(mlblr)  # Prints "4"
mlblr *= 2
print(mlblr)  # Prints "8"
eip = 2.5
print(type(eip)) # Prints "<class 'float'>"
print(eip, eip + 1, eip * 2, eip ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'int'>
3
4
2
6
9
4
8
<class 'float'>
2.5 3.5 5.0 6.25


In [ ]:
#Note that unlike many languages, Python does not have unary increment (x++) or decrement (x--) operators.

#Python also has built-in types for complex numbers; you can find all of the details in the documentation.

#Booleans: Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (&&, ||, etc.):

In [5]:
eip_in = True
eip_out = False
print(type(eip_in)) # Prints "<class 'bool'>"
print(eip_in and eip_out) # Logical AND; prints "False"
print(eip_in or eip_out)  # Logical OR; prints "True"
print(not eip_in)   # Logical NOT; prints "False"
print(eip_in != eip_out)  # Logical XOR; prints "True"

<class 'bool'>
False
True
False
True


In [9]:
eip = 'hello'    # String literals can use single quotes
mlblr = "world"    # or double quotes; it does not matter.
print(eip)       # Prints "hello"
print(len(eip))  # String length; prints "5"
mlblr_in = eip + ' ' + mlblr  # String concatenation
print(mlblr_in)  # prints "hello world"
eip_in = '%s %s %d' % (eip, mlblr, 12)  # sprintf style string formatting
print(eip_in)  # prints "hello world 12"

hello
5
hello world
hello world 12


In [10]:
mlblr = "hello"
print(mlblr.capitalize())  # Capitalize a string; prints "Hello"
print(mlblr.upper())       # Convert a string to uppercase; prints "HELLO"
print(mlblr.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(mlblr.center(7))     # Center a string, padding with spaces; prints " hello "
print(mlblr.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


In [11]:
eip = [3, 1, 2]    # Create a list
print(eip, eip[2])  # Prints "[3, 1, 2] 2"
print(eip[-1])     # Negative indices count from the end of the list; prints "2"
eip[2] = 'foo'     # Lists can contain elements of different types
print(eip)         # Prints "[3, 1, 'foo']"
eip.append('bar')  # Add a new element to the end of the list
print(eip)         # Prints "[3, 1, 'foo', 'bar']"
x = eip.pop()      # Remove and return the last element of the list
print(x, eip)      # Prints "bar [3, 1, 'foo']"

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


In [12]:
mlblr = list(range(5))     # range is a built-in function that creates a list of integers
print(mlblr)               # Prints "[0, 1, 2, 3, 4]"
print(mlblr[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(mlblr[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(mlblr[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(mlblr[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(mlblr[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
mlblr[2:4] = [8, 9]        # Assign a new sublist to a slice
print(mlblr)               # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


In [14]:
eip = ['cat', 'dog', 'monkey']
for mlblr in eip:
    print(mlblr)
# Prints "cat", "dog", "monkey", each on its own line.

cat
dog
monkey


In [16]:
eip = ['cat', 'dog', 'monkey']
for num, mlblr in enumerate(eip):
    print('%d: %s' % (num + 1, mlblr))
# Prints "#1: cat", "#2: dog", "#3: monkey", each on its own line

1: cat
2: dog
3: monkey


In [17]:
mlblr = [0, 1, 2, 3, 4]
eip = []
for x in mlblr:
    eip.append(x ** 2)
print(eip)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


In [18]:
mlblr = [0, 1, 2, 3, 4]
eip = [x ** 2 for x in mlblr]
print(eip)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


In [20]:
mlblr = [0, 1, 2, 3, 4]
eip = [x ** 2 for x in mlblr if x % 2 == 0]
print(eip)  # Prints "[0, 4, 16]"

[0, 4, 16]


In [22]:
eip = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(eip['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in eip)     # Check if a dictionary has a given key; prints "True"
eip['fish'] = 'wet'     # Set an entry in a dictionary
print(eip['fish'])      # Prints "wet"
# print(d['monkey'])  # KeyError: 'monkey' not a key of d
print(eip.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(eip.get('fish', 'N/A'))    # Get an element with a default; prints "wet"
del eip['fish']         # Remove an element from a dictionary
print(eip.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

cute
True
wet
N/A
wet
N/A


In [24]:
eip = {'person': 2, 'cat': 4, 'spider': 8}
for mlblr in eip:
    legs = eip[mlblr]
    print('A %s has %d legs' % (mlblr, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [26]:
eip = {'person': 2, 'cat': 4, 'spider': 8}
for mlblr, eip_in in eip.items():
    print('A %s has %d legs' % (mlblr, eip_in))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [27]:
mlblr = [0, 1, 2, 3, 4]
eip_in = {x: x ** 2 for x in mlblr if x % 2 == 0}
print(eip_in)  # Prints "{0: 0, 2: 4, 4: 16}"

{0: 0, 2: 4, 4: 16}


In [28]:
mlblr = {'cat', 'dog'}
print('cat' in mlblr)   # Check if an element is in a set; prints "True"
print('fish' in mlblr)  # prints "False"
mlblr.add('fish')       # Add an element to a set
print('fish' in mlblr)  # Prints "True"
print(len(mlblr))       # Number of elements in a set; prints "3"
mlblr.add('cat')        # Adding an element that is already in the set does nothing
print(len(mlblr))       # Prints "3"
mlblr.remove('cat')     # Remove an element from a set
print(len(mlblr))       # Prints "2"

True
False
True
3
3
2


In [29]:
mlblr = {'cat', 'dog', 'fish'}
for idx, eip_in in enumerate(mlblr):
    print('#%d: %s' % (idx + 1, eip_in))
# Prints "#1: fish", "#2: dog", "#3: cat"

#1: cat
#2: dog
#3: fish


In [33]:
from math import sqrt
mlblr = {int(sqrt(eip)) for eip in range(30)}
print(mlblr)  # Prints "{0, 1, 2, 3, 4, 5}"

{0, 1, 2, 3, 4, 5}


In [34]:
mlblr = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
eip = (5, 6)        # Create a tuple
print(type(eip))    # Prints "<class 'tuple'>"
print(mlblr[eip])       # Prints "5"
print(mlblr[(1, 2)])  # Prints "1"

<class 'tuple'>
5
1


In [36]:
def mlblr(eip):
    if eip > 0:
        return 'positive'
    elif eip < 0:
        return 'negative'
    else:
        return 'zero'

for eip in [-1, 0, 1]:
    print(mlblr(eip))
# Prints "negative", "zero", "positive"

negative
zero
positive


In [37]:
def mlblr(name, eip=False):
    if eip:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

mlblr('Bob') # Prints "Hello, Bob"
mlblr('Fred', eip=True)  # Prints "HELLO, FRED!"

Hello, Bob
HELLO, FRED!


In [38]:
class mlblr(object):

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

eip = mlblr('Fred')  # Construct an instance of the Greeter class
eip.greet()            # Call an instance method; prints "Hello, Fred"
eip.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

Hello, Fred
HELLO, FRED!


In [39]:
import numpy as np

mlblr = np.array([1, 2, 3])   # Create a rank 1 array
print(type(mlblr))            # Prints "<class 'numpy.ndarray'>"
print(mlblr.shape)            # Prints "(3,)"
print(mlblr[0], mlblr[1], mlblr[2])   # Prints "1 2 3"
mlblr[0] = 5                  # Change an element of the array
print(mlblr)                  # Prints "[5, 2, 3]"

eip = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(eip.shape)                     # Prints "(2, 3)"
print(eip[0, 0], eip[0, 1], eip[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [40]:
import numpy as np

mlblr = np.zeros((2,2))   # Create an array of all zeros
print(mlblr)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

eip = np.ones((1,2))    # Create an array of all ones
print(eip)              # Prints "[[ 1.  1.]]"

eip_in = np.full((2,2), 7)  # Create a constant array
print(eip_in)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

mlblr_in = np.eye(2)         # Create a 2x2 identity matrix
print(mlblr_in)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

eip_out = np.random.random((2,2))  # Create an array filled with random values
print(eip_out)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.15845022 0.32741231]
 [0.22357309 0.20987546]]


In [46]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
mlblr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
eip = mlblr[:2, 1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(mlblr[0, 1])   # Prints "2"
eip[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(mlblr[0, 1])   # Prints "77"

[[77  3]
 [ 6  7]]
2
77


In [47]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
mlblr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
eip_in = mlblr[1, :]    # Rank 1 view of the second row of a
eip_out = mlblr[1:2, :]  # Rank 2 view of the second row of a
print(eip_in, eip_in.shape)  # Prints "[5 6 7 8] (4,)"
print(eip_out, eip_out.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
mlblr_in = mlblr[:, 1]
mlblr_out = mlblr[:, 1:2]
print(mlblr_in, mlblr_in.shape)  # Prints "[ 2  6 10] (3,)"
print(mlblr_out, mlblr_out.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [48]:
import numpy as np

mlblr = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(mlblr[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([mlblr[0, 0], mlblr[1, 1], mlblr[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(mlblr[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([mlblr[0, 1], mlblr[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [52]:
import numpy as np

# Create a new array from which we will select elements
mlblr = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(mlblr)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
eip = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(mlblr[np.arange(4), eip])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
mlblr[np.arange(4), eip] += 10

print(mlblr)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[0 2 0 1] kk
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [53]:
import numpy as np

mlblr = np.array([[1,2], [3, 4], [5, 6]])

eip = (mlblr > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(eip)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(mlblr[eip])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(mlblr[mlblr > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [54]:
import numpy as np

mlblr = np.array([1, 2])   # Let numpy choose the datatype
print(mlblr.dtype)         # Prints "int64"

mlblr = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(mlblr.dtype)             # Prints "float64"

mlblr = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(mlblr.dtype)                         # Prints "int64"

int64
float64
int64


In [55]:
import numpy as np

mlblr = np.array([[1,2],[3,4]], dtype=np.float64)
eip = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(mlblr + eip)
print(np.add(mlblr, eip))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(mlblr - eip)
print(np.subtract(mlblr, eip))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(mlblr * eip)
print(np.multiply(mlblr, eip))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(mlblr / eip)
print(np.divide(mlblr, eip))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(mlblr))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [57]:
import numpy as np

mlblr = np.array([[1,2],[3,4]])
eip = np.array([[5,6],[7,8]])

mlblr_in = np.array([9,10])
eip_in = np.array([11, 12])

# Inner product of vectors; both produce 219
print(mlblr_in.dot(eip_in))
print(np.dot(mlblr_in, eip_in))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(mlblr.dot(mlblr_in))
print(np.dot(mlblr, mlblr_in))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(mlblr.dot(eip))
print(np.dot(mlblr, eip))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [58]:
import numpy as np

mlblr = np.array([[1,2],[3,4]])

print(np.sum(mlblr))  # Compute sum of all elements; prints "10"
print(np.sum(mlblr, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(mlblr, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [60]:
import numpy as np

mlblr = np.array([[1,2], [3,4]])
print(mlblr)    # Prints "[[1 2]
            #          [3 4]]"
print(mlblr.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
eip = np.array([1,2,3])
print(eip)    # Prints "[1 2 3]"
print(eip.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [63]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
mlblr = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
mlblr_in = np.array([1, 0, 1])
eip = np.empty_like(mlblr)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    eip[i, :] = mlblr[i, :] + mlblr_in

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(eip)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [64]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
mlblr = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
eip = np.array([1, 0, 1])
eip_in = np.tile(eip, (4, 1))   # Stack 4 copies of v on top of each other
print(eip_in)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
eip = mlblr + eip_in  # Add x and vv elementwise
print(eip)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [66]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
mlblr = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
eip = np.array([1, 0, 1])
eip_in = mlblr + eip  # Add v to each row of x using broadcasting
print(eip_in)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [23]:
import numpy as np

# Compute outer product of vectors
eip = np.array([1,2,3])  # v has shape (3,)
eip_in = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(eip, (3, 1)) * eip_in)

# Add a vector to each row of a matrix
mlblr = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(mlblr + eip)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((mlblr.T + eip_in).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(mlblr + np.reshape(eip_in, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(mlblr * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


In [21]:
from scipy.misc import imread, imsave, imresize

# Read an JPEG image into a numpy array
mlblr = imread('2.jpg')
print(mlblr.dtype, mlblr.shape)  # Prints "uint8 (400, 248, 3)"

# We can tint the image by scaling each of the color channels
# by a different scalar constant. The image has shape (400, 248, 3);
# we multiply it by the array [1, 0.95, 0.9] of shape (3,);
# numpy broadcasting means that this leaves the red channel unchanged,
# and multiplies the green and blue channels by 0.95 and 0.9
# respectively.
eip = mlblr * [1, 0.95, 0.9]

# Resize the tinted image to be 300 by 300 pixels.
eip = imresize(eip, (300, 300))

# Write the tinted image back to disk
imsave('images/cat_tinted.jpg', img_tinted)

uint8 (467, 700, 3)


/home/balaji/py3/lib/python3.6/site-packages/scipy/misc/pilutil.py:482: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if issubdtype(ts, int):
/home/balaji/py3/lib/python3.6/site-packages/scipy/misc/pilutil.py:485: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif issubdtype(type(size), float):


In [70]:
import numpy as np
from scipy.spatial.distance import pdist, squareform

# Create the following array where each row is a point in 2D space:
# [[0 1]
#  [1 0]
#  [2 0]]
mlblr = np.array([[0, 1], [1, 0], [2, 0]])
print(mlblr)

# Compute the Euclidean distance between all rows of x.
# d[i, j] is the Euclidean distance between x[i, :] and x[j, :],
# and d is the following array:
# [[ 0.          1.41421356  2.23606798]
#  [ 1.41421356  0.          1.        ]
#  [ 2.23606798  1.          0.        ]]
eip = squareform(pdist(mlblr, 'euclidean'))
print(eip)

[[0 1]
 [1 0]
 [2 0]]
[[0.         1.41421356 2.23606798]
 [1.41421356 0.         1.        ]
 [2.23606798 1.         0.        ]]


In [20]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib

# Compute the x and y coordinates for points on a sine curve
mlblr = np.arange(0, 3 * np.pi, 0.1)
eip = np.sin(x)

# Plot the points using matplotlib
plt.plot(mlblr, eip)
plt.show()  # You must call plt.show() to make graphics appear.

Using matplotlib backend: TkAgg


In [19]:
import numpy as np
import matplotlib.pyplot as plt

# Compute the x and y coordinates for points on sine and cosine curves
mlblr = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(mlblr)
y_cos = np.cos(mlblr)

# Plot the points using matplotlib
plt.plot(mlblr, y_sin)
plt.plot(mlblr, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])
plt.show()

In [10]:
import numpy as np
import matplotlib.pyplot as plt

# Compute the x and y coordinates for points on sine and cosine curves
mlblr = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(mlblr, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()

In [18]:
import numpy as np
from scipy.misc import imread, imresize
import matplotlib.pyplot as plt

mlblr = imread('2.jpg')
eip = img * [1, 0.95, 0.9]

# Show the original image
plt.subplot(1, 2, 1)
plt.imshow(mlblr)

# Show the tinted image
plt.subplot(1, 2, 2)

# A slight gotcha with imshow is that it might give strange results
# if presented with data that is not uint8. To work around this, we
# explicitly cast the image to uint8 before displaying it.
plt.imshow(np.uint8(eip))
plt.show()